// <auto-generated />
using System;
using Ecom.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecom.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250403170744_danh_gia")]
    partial class danh_gia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecom.Entity.account", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("dia_chi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("dvvc_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("dvvcid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("gioi_tinh")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_super_admin")
                        .HasColumnType("bit");

                    b.Property<string>("mat_khau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("so_dien_thoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tai_khoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("trang_thai")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("dvvcid");

                    b.ToTable("account");
                });

            modelBuilder.Entity("Ecom.Entity.anh_san_pham", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("duong_dan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ma_san_pham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("san_Phamid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("san_pham_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.HasIndex("san_Phamid");

                    b.ToTable("anh_san_pham");
                });

            modelBuilder.Entity("Ecom.Entity.chi_tiet_don_hang", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Don_Hangid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("San_phamid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("don_gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("don_hang_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("san_pham_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("so_luong")
                        .HasColumnType("int");

                    b.Property<decimal>("thanh_tien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("Don_Hangid");

                    b.HasIndex("San_phamid");

                    b.ToTable("chi_tiet_don_hang");
                });

            modelBuilder.Entity("Ecom.Entity.chi_tiet_gio_hang", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Gio_Hangid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("San_Phamid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("gio_hang_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("san_pham_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("so_luong")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Gio_Hangid");

                    b.HasIndex("San_Phamid");

                    b.ToTable("chi_tiet_gio_hang");
                });

            modelBuilder.Entity("Ecom.Entity.chi_tiet_phieu_nhap_kho", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("don_gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ma_san_pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("phieu_nhap_kho_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("phieu_nhap_khoid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("san_pham_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("san_phamid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("so_luong")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("phieu_nhap_khoid");

                    b.HasIndex("san_phamid");

                    b.ToTable("chi_tiet_phieu_nhap_kho");
                });

            modelBuilder.Entity("Ecom.Entity.chuong_trinh_marketing", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cong_cu")
                        .HasColumnType("int");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("chuong_trinh_marketing");
                });

            modelBuilder.Entity("Ecom.Entity.danh_gia", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Accountid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("San_Phamid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("account_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("danh_gia_chat_luong")
                        .HasColumnType("int");

                    b.Property<string>("ma_san_pham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noi_dung_danh_gia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noi_dung_phan_hoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("san_pham_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.HasIndex("Accountid");

                    b.HasIndex("San_Phamid");

                    b.ToTable("danh_gia");
                });

            modelBuilder.Entity("Ecom.Entity.danh_muc", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ma_danh_muc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_danh_muc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("danh_muc");
                });

            modelBuilder.Entity("Ecom.Entity.don_hang", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Accountid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Dvvcid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("account_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("dia_chi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("dvvc_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("is_danh_gia")
                        .HasColumnType("bit");

                    b.Property<string>("ma_don_hang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_mua")
                        .HasColumnType("datetime2");

                    b.Property<string>("so_dien_thoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("thanh_tien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tong_tien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Accountid");

                    b.HasIndex("Dvvcid");

                    b.ToTable("don_hang");
                });

            modelBuilder.Entity("Ecom.Entity.dvvc", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("dvvc");
                });

            modelBuilder.Entity("Ecom.Entity.gio_hang", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Accountid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("account_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.HasIndex("Accountid");

                    b.ToTable("gio_hang");
                });

            modelBuilder.Entity("Ecom.Entity.lich_su_giao_dich", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("giao_dich")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("loai_giao_dich")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ngay_giao_dich")
                        .HasColumnType("datetime2");

                    b.Property<int?>("phuong_thuc_giao_dich")
                        .HasColumnType("int");

                    b.Property<decimal>("so_du")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("lich_su_giao_dich");
                });

            modelBuilder.Entity("Ecom.Entity.ma_giam_gia", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("bat_dau")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("giam_gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ket_thuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("so_luong")
                        .HasColumnType("int");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ma_gia_gia");
                });

            modelBuilder.Entity("Ecom.Entity.ngan_hang", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("account_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("accountid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("is_default")
                        .HasColumnType("bit");

                    b.Property<string>("so_tai_khoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("so_the")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_ngan_hang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_tai_khoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("accountid");

                    b.ToTable("ngan_hang");
                });

            modelBuilder.Entity("Ecom.Entity.phieu_nhap_kho", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ghi_chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_du_kien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngay_het_han")
                        .HasColumnType("datetime2");

                    b.Property<string>("nha_cung_cap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("thanh_tien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("phieu_nhap_kho");
                });

            modelBuilder.Entity("Ecom.Entity.san_pham", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("danh_Mucid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("danh_muc_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("duong_dan_anh_bia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.Property<decimal?>("khuyen_mai")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("luot_ban")
                        .HasColumnType("int");

                    b.Property<string>("ma_san_pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mau_sac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("so_luong")
                        .HasColumnType("int");

                    b.Property<string>("ten_san_pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xuat_xu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("danh_Mucid");

                    b.ToTable("san_pham");
                });

            modelBuilder.Entity("Ecom.Entity.thong_bao", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("accountid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("nguoi_dung_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("nhom")
                        .HasColumnType("int");

                    b.Property<string>("noi_dung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("thoi_gian_doc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("trang_thai")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("accountid");

                    b.ToTable("thong_bao");
                });

            modelBuilder.Entity("Ecom.Entity.account", b =>
                {
                    b.HasOne("Ecom.Entity.dvvc", "dvvc")
                        .WithMany()
                        .HasForeignKey("dvvcid");

                    b.Navigation("dvvc");
                });

            modelBuilder.Entity("Ecom.Entity.anh_san_pham", b =>
                {
                    b.HasOne("Ecom.Entity.san_pham", "san_Pham")
                        .WithMany("ds_anh_san_pham")
                        .HasForeignKey("san_Phamid");

                    b.Navigation("san_Pham");
                });

            modelBuilder.Entity("Ecom.Entity.chi_tiet_don_hang", b =>
                {
                    b.HasOne("Ecom.Entity.don_hang", "Don_Hang")
                        .WithMany()
                        .HasForeignKey("Don_Hangid");

                    b.HasOne("Ecom.Entity.san_pham", "San_pham")
                        .WithMany()
                        .HasForeignKey("San_phamid");

                    b.Navigation("Don_Hang");

                    b.Navigation("San_pham");
                });

            modelBuilder.Entity("Ecom.Entity.chi_tiet_gio_hang", b =>
                {
                    b.HasOne("Ecom.Entity.gio_hang", "Gio_Hang")
                        .WithMany()
                        .HasForeignKey("Gio_Hangid");

                    b.HasOne("Ecom.Entity.san_pham", "San_Pham")
                        .WithMany()
                        .HasForeignKey("San_Phamid");

                    b.Navigation("Gio_Hang");

                    b.Navigation("San_Pham");
                });

            modelBuilder.Entity("Ecom.Entity.chi_tiet_phieu_nhap_kho", b =>
                {
                    b.HasOne("Ecom.Entity.phieu_nhap_kho", "phieu_nhap_kho")
                        .WithMany("ds_chi_tiet_phieu_nhap_kho")
                        .HasForeignKey("phieu_nhap_khoid");

                    b.HasOne("Ecom.Entity.san_pham", "san_pham")
                        .WithMany()
                        .HasForeignKey("san_phamid");

                    b.Navigation("phieu_nhap_kho");

                    b.Navigation("san_pham");
                });

            modelBuilder.Entity("Ecom.Entity.danh_gia", b =>
                {
                    b.HasOne("Ecom.Entity.account", "Account")
                        .WithMany()
                        .HasForeignKey("Accountid");

                    b.HasOne("Ecom.Entity.san_pham", "San_Pham")
                        .WithMany()
                        .HasForeignKey("San_Phamid");

                    b.Navigation("Account");

                    b.Navigation("San_Pham");
                });

            modelBuilder.Entity("Ecom.Entity.don_hang", b =>
                {
                    b.HasOne("Ecom.Entity.account", "Account")
                        .WithMany()
                        .HasForeignKey("Accountid");

                    b.HasOne("Ecom.Entity.dvvc", "Dvvc")
                        .WithMany()
                        .HasForeignKey("Dvvcid");

                    b.Navigation("Account");

                    b.Navigation("Dvvc");
                });

            modelBuilder.Entity("Ecom.Entity.gio_hang", b =>
                {
                    b.HasOne("Ecom.Entity.account", "Account")
                        .WithMany()
                        .HasForeignKey("Accountid");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Ecom.Entity.ngan_hang", b =>
                {
                    b.HasOne("Ecom.Entity.account", "account")
                        .WithMany()
                        .HasForeignKey("accountid");

                    b.Navigation("account");
                });

            modelBuilder.Entity("Ecom.Entity.san_pham", b =>
                {
                    b.HasOne("Ecom.Entity.danh_muc", "danh_Muc")
                        .WithMany()
                        .HasForeignKey("danh_Mucid");

                    b.Navigation("danh_Muc");
                });

            modelBuilder.Entity("Ecom.Entity.thong_bao", b =>
                {
                    b.HasOne("Ecom.Entity.account", "account")
                        .WithMany()
                        .HasForeignKey("accountid");

                    b.Navigation("account");
                });

            modelBuilder.Entity("Ecom.Entity.phieu_nhap_kho", b =>
                {
                    b.Navigation("ds_chi_tiet_phieu_nhap_kho");
                });

            modelBuilder.Entity("Ecom.Entity.san_pham", b =>
                {
                    b.Navigation("ds_anh_san_pham");
                });
#pragma warning restore 612, 618
        }
    }
}
